version: "3.7"
services:
  configserver:
    build: ../configuration-server
    container_name: config-server-latest
    image: configuration-server:latest
    ports:
      - "8071:8071"
    networks:
      backend:
        aliases:
          - "configserver"
  eurekaserver:
    build: ../eureka-server
    image: eureka-server:latest
    container_name: eureka-server-latest
    ports:
      - "8070:8070"
    networks:
      backend:
        aliases:
          - "eurekaserver"
networks:
  backend:
    driver: bridge
