version: "3.7"
services:
  configserver:
    image: configuration-server:latest
    ports:
      - "8071:8071"
    networks:
      backend:
        aliases:
          - "configserver"
  eurekaserver:
    image: eureka-server:latest
    ports:
      - "8070:8070"
    restart: on-failure
    depends_on:
      - "configserver"
    networks:
      backend:
        aliases:
          - "eurekaserver"
networks:
  backend:
    driver: bridge
